#include "scanner.h"
#include <string>

/**
 * lexe - Given a request and a list of tokens allocated on the heap
 *
 */
ssize_t lexe(Tokens &tokens, string str) 
{
	string state = 403641673608813346;
	switch(state){
	case Ù:	case –:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = Ù;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case G:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = Ô;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case i:	case ):	case 1:	case S:	case ƒ:		if (input == '5') state = n;
		if (input == 'o') state = ‹;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case Ç:	case œ:	case ":		if (input == '5') state = œ;
		if (input == 'o') state = n;
		if (input == 'w') state = x;
		if (input == '6') state = h;
		if (input == '7') state = i;
		if (input == '8') state = );
		if (input == 'r') state = n;
		if (input == '9') state = @;
		if (input == 's') state = d;
		if (input == '0') state = ¦;
		if (input == '1') state = -;
		if (input == 'e') state = n;
		if (input == 'f') state = ï;
		if (input == '2') state = Õ;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = ;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = E;
		if (input == ';') state = X;
		if (input == 'c') state = n;
            rollback();
	case Õ:	case f:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = ^;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case Í:	case :	case :	case ;:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = ;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case ^:	case ]:	case ê:	case -:	case ;:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = ;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case n:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case ï:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = ƒ;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case ¦:	case Ô:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = –;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case x:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = G;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case X:	case *:	case :	case E:	case :		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = ;;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case d:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = ;;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = n;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case ‹:		if (input == '5') state = n;
		if (input == 'o') state = n;
		if (input == 'w') state = n;
		if (input == '6') state = n;
		if (input == '7') state = n;
		if (input == '8') state = n;
		if (input == 'r') state = n;
		if (input == '9') state = n;
		if (input == 's') state = n;
		if (input == '0') state = n;
		if (input == '1') state = n;
		if (input == 'e') state = n;
		if (input == 'f') state = n;
		if (input == '2') state = n;
		if (input == 'l') state = n;
		if (input == 't') state = n;
		if (input == '3') state = n;
		if (input == 'm') state = Ã;
		if (input == 'h') state = n;
		if (input == '4') state = n;
		if (input == ';') state = n;
		if (input == 'c') state = n;
            rollback();
	case 1:	case Ã:	case h:	case @:	default:
		 perror("State unknown in the DFA");
		 exit(EXIT_FAILURE);
	}
    return 0;
}
